name: CustomEnderChest
main: org.maiminhdung.customenderchest.EnderChest
version: 2.0.6-test
author: maiminhdung, brunyman
website: https://maiminhdung.dev/
load: STARTUP
api-version: 1.20
folia-supported: true
commands:
    customenderchest:
        description: Main command for CustomEnderChest.
        usage: "/<command> [open|reload|admin]"
        aliases: [ cec, ec, customec ]
permissions:
    CustomEnderChest.level.0:
        description: 9 slots enderchest (1 raw).
        default: false
    CustomEnderChest.level.1:
        description: 18 slots enderchest (2 raws).
        default: false
    CustomEnderChest.level.2:
        description: 27 slots enderchest (3 raws).
        default: false
    CustomEnderChest.level.3:
        description: 36 slots enderchest (4 raws).
        default: false
    CustomEnderChest.level.4:
        description: 45 slots enderchest (5 raws).
        default: false
    CustomEnderChest.level.5:
        description: 54 slots enderchest (6 raws).
        default: op
    CustomEnderChest.command.open.self:
        description: Allows opening your own chest with /cec open.
        default: false
    CustomEnderChest.command.open.other:
            description: Allows opening other players' chests.
            default: op
    CustomEnderChest.command.delete:
            description: Allows deleting player data.
            default: op
    CustomEnderChest.admin:
            description: Administrative access for reload and import commands.
            default: op
    CustomEnderChest.commands:
        description: Open your enderchest via command.
        default: op